description: Hooks that interface with tackle's parser and context. Core to most tackle scripts.

examples:
  - name: Basic
    description: The most minimal implementation
    content: |
      example:
        type: provider_docs
        chdir: ".."
        provider: docs

hook_examples:
  tackle:
    - name: Basic
      description: The most minimal implementation
      content: |
        example:
          type: provider_docs
          chdir: ".."
          provider: docs
