name: Time Provider

description: Hooks that work with date and time

examples:
#  - name: "[time_now](time.md)"
#    description: Get a map with keys of kubernetes context names and values with details from KUBECONFIG environment variable.
#    content: |
#      compact->: k8s_current_context


hook_examples:
#  print:
#    - name: Compact print - most common use
#      content: |
#        compact->: print stuff and things
#    - name: Expanded print
#      content: |
#        expanded:
#          ->: print
#          objects: stuff and
#          end: " "
#        compact->: print things
#      output_text: |
#        stuff and things

