
name: TOML Provider

description: |
  Reading toml files. For writing toml you will need a third party provider since this wraps python's native toml library which only supports reads.

examples: []

hook_examples:
  toml:
    - name: Read toml
      description: Read a toml file into a key
      content: |
        expanded:
          ->: toml
          path: path/to/toml/file.toml
        compact->: toml path/to/toml/file.toml
