name: tests

on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        name:
          - "linting"
          - "ubuntu-py38"
          - "ubuntu-py39"
          - "ubuntu-py310"
          - "ubuntu-py312"
          - "macos-py38"
          - "macos-py39"
          - "macos-py310"
          - "macos-py312"

        include:
          - name: "linting"
            python: "3.8"
            os: ubuntu-latest
            tox_env: "lint"
          - name: "ubuntu-py38"
            python: "3.8"
            os: ubuntu-latest
            tox_env: "py38"
          - name: "ubuntu-py39"
            python: "3.9"
            os: ubuntu-latest
            tox_env: "py39"
          - name: "ubuntu-py310"
            python: "3.10"
            os: ubuntu-latest
            tox_env: "py310"
          - name: "ubuntu-py312"
            python: "3.12"
            os: ubuntu-latest
            tox_env: "py312"
          - name: "macos-py38"
            python: "3.8"
            os: macos-latest
            tox_env: "py38"
          - name: "macos-py39"
            python: "3.9"
            os: macos-latest
            tox_env: "py39"
          - name: "macos-py310"
            python: "3.10"
            os: macos-latest
            tox_env: "py310"
          - name: "macos-py312"
            python: "3.12"
            os: macos-latest
            tox_env: "py312"

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox virtualenv
      - name: Test build
        run: "tox -e ${{ matrix.tox_env }}"
