name: File Provider

description: Hooks that operate on the files.

examples:
  - name: "[copy](copy.md)"
    description: Copy a file or directory single file
    content: |
      compact->: copy path/to/file output/path
      expanded:
        ->: jinja
        template: path/to/file
        output: output/path

  - name: "[chmod](chmod.md)"
    description: Change directory permissions
    content->: file tests/file/chmod.yaml

hook_examples:
  generate:
    - name: Basic
      description: The most minimal implementation. By default, the render context is the current context.
      content: |
        generate_example->: generate path/to/template/file/or/dir output/path

    - name: With specific context
      description: Sometimes you want to render with a specific context.
      content: |
        generate_example:
          ->: generate path/to/template/file/or/dir output/path
          render_context: # Could simply be {{ some.other.key }}
            foo: bar
            stuff:
              - things

    - name: With additional context
      description: Sometimes you want to render by re-keying some of the context. In this case the additional context is a list of maps that is merged together.
      content: |
        generate_example:
          ->: generate path/to/template/file/or/dir output/path
          additional_context:
            - "{{ render_context }}"
            - "{{ other_context }}"

    - name: Copy without render
      description: In case you don't want to render a file (for example a template), you can copy without rendering.
      content: |
        expanded:
          ->: generate render_src output
          copy_without_render:
            - ./render_src/.hidden.yaml
            - ./render_src/no-render/*

  jinja:
    - name: Basic
      description: The most minimal implementation.
      content: |
        jinja_example->: jinja path/to/template/file/or/dir output/path

    - name: With context specific
      description: Sometimes you want to render with a specific context.
      content: |
        jinja_example:
          ->: jinja path/to/template/file/or/dir output/path
          render_context: # Could simply be {{ some.other.key }}
            foo: bar
            stuff:
              - things
